// <auto-generated />
namespace CalculationEngineService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_property));
        
        string IMigrationMetadata.Id
        {
            get { return "202007022231183_Add_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
