//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Coordinate reference system.
    public class CoordinateSystem : IDClass {
        
        /// Location described by using position points in this coordinate system.
        private Location cim_Location;
        
        private const bool isLocationMandatory = true;
        
        private const string _LocationPrefix = "cim";
        
        /// Name of this coordinate system.
        private string cim_name;
        
        private const bool isNameMandatory = true;
        
        private const string _namePrefix = "cim";
        
        public virtual Location Location {
            get {
                return this.cim_Location;
            }
            set {
                this.cim_Location = value;
            }
        }
        
        public virtual bool LocationHasValue {
            get {
                return this.cim_Location != null;
            }
        }
        
        public static bool IsLocationMandatory {
            get {
                return isLocationMandatory;
            }
        }
        
        public static string LocationPrefix {
            get {
                return _LocationPrefix;
            }
        }
        
        public virtual string Name {
            get {
                return this.cim_name;
            }
            set {
                this.cim_name = value;
            }
        }
        
        public virtual bool NameHasValue {
            get {
                return this.cim_name != null;
            }
        }
        
        public static bool IsNameMandatory {
            get {
                return isNameMandatory;
            }
        }
        
        public static string NamePrefix {
            get {
                return _namePrefix;
            }
        }
    }
}
