//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// The place, scene, or point of something where someone or something has been, is, and/or will be at a given moment in time. It is defined with one or more postition points (coordinates) in a given coordinate system.
    public class Location : IdentifiedObject {
        
        /// Category by utility's corporate standards and practices, relative to the location itself (e.g., geographical, functional accounting, etc., not a given property that happens to exist at that location).
        private string cim_category;
        
        private const bool isCategoryMandatory = true;
        
        private const string _categoryPrefix = "cim";
        
        /// Utility-specific code for the location.
        private string cim_corporateCode;
        
        private const bool isCorporateCodeMandatory = false;
        
        private const string _corporateCodePrefix = "cim";
        
        public virtual string Category {
            get {
                return this.cim_category;
            }
            set {
                this.cim_category = value;
            }
        }
        
        public virtual bool CategoryHasValue {
            get {
                return this.cim_category != null;
            }
        }
        
        public static bool IsCategoryMandatory {
            get {
                return isCategoryMandatory;
            }
        }
        
        public static string CategoryPrefix {
            get {
                return _categoryPrefix;
            }
        }
        
        public virtual string CorporateCode {
            get {
                return this.cim_corporateCode;
            }
            set {
                this.cim_corporateCode = value;
            }
        }
        
        public virtual bool CorporateCodeHasValue {
            get {
                return this.cim_corporateCode != null;
            }
        }
        
        public static bool IsCorporateCodeMandatory {
            get {
                return isCorporateCodeMandatory;
            }
        }
        
        public static string CorporateCodePrefix {
            get {
                return _corporateCodePrefix;
            }
        }
    }
}
