//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum PhaseCode {
        
        A,
        
        AB,
        
        ABC,
        
        ABCN,
        
        ABN,
        
        AC,
        
        ACN,
        
        AN,
        
        B,
        
        BC,
        
        BCN,
        
        BN,
        
        C,
        
        CN,
        
        N,
        
        /// Secondary phases 1, 2, and neutral.
        s12N,
        
        /// Secondary phase 1 and neutral.
        s1N,
        
        /// Secondary phase 2 and neutral.
        s2N,
    }
}
