//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// A power system resource can be an item of equipment such as a Switch, an EquipmentContainer containing many individual items of equipment such as a 
    ///Substation, or an organisational entity such as Company or SubControlArea.  This provides for the nesting of collections of PowerSystemResources within other PowerSystemResources. For example, a Switch could be a member of a Substation and a Substation could be a member of a division of a Company.
    public class PowerSystemResource : IdentifiedObject {
        
        /// Custom (project-specific) type of this object. For example, all supply transformers, regardless of winding count, can have a custom type named "Supply transformer".
        private string cim_customType;
        
        private const bool isCustomTypeMandatory = false;
        
        private const string _customTypePrefix = "ftn";
        
        /// Location of this power system resource.
        private Location cim_Location;
        
        private const bool isLocationMandatory = false;
        
        private const string _LocationPrefix = "cim";
        
        public virtual string CustomType {
            get {
                return this.cim_customType;
            }
            set {
                this.cim_customType = value;
            }
        }
        
        public virtual bool CustomTypeHasValue {
            get {
                return this.cim_customType != null;
            }
        }
        
        public static bool IsCustomTypeMandatory {
            get {
                return isCustomTypeMandatory;
            }
        }
        
        public static string CustomTypePrefix {
            get {
                return _customTypePrefix;
            }
        }
        
        public virtual Location Location {
            get {
                return this.cim_Location;
            }
            set {
                this.cim_Location = value;
            }
        }
        
        public virtual bool LocationHasValue {
            get {
                return this.cim_Location != null;
            }
        }
        
        public static bool IsLocationMandatory {
            get {
                return isLocationMandatory;
            }
        }
        
        public static string LocationPrefix {
            get {
                return _LocationPrefix;
            }
        }
    }
}
