// <auto-generated />
namespace CalculationEngineServ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProfitAndCO2Reduction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfitAndCO2Reduction));
        
        string IMigrationMetadata.Id
        {
            get { return "202009191147199_ProfitAndCO2Reduction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
